apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress
        name: wordpress
        envFrom:
          - configMapRef:
              name: wp-config
        env:
         - name: WORDPRESS_DB_PASSWORD
           valueFrom:
             secretKeyRef:
               name: wp-secret
               key: password
        resources: {}
status: {}
